### ISSUE TITLE
Basic TODO list

### ISSUE THREAD

**Issue by GinBlades** [GinBlades/notes#1]
- [ ] Make Notebooks
    - [ ] Create
    - [ ] Index
    - [ ] Show
    - [ ] Update
    - [ ] Delete
- [ ] Make Notes
    - [ ] Create
    - [ ] Index
    - [ ] Show
    - [ ] Update
    - [ ] Delete
- [ ] Make Home
    - [ ] Show Recent Notes and Notebooks
    - [ ] Search Notes and Notebooks
- [ ] Make profile page
- [ ] Make Friends
    - [ ] Show public notes
    - [ ] Connect to friends
    - [ ] Show friends shared notes
- [ ] Rethink Authentication
- [ ] Setup deploy script, including gulp
- [ ] Add TinyMCE
- [ ] Add Ace
- [ ] Add comments
- [ ] Add paper trail for versioning / diffing
